/*
** syscall.c for  in /home/karmes_l/Projets/tek2/Systeme_Unix-Instrumentation/PSU_2015_strace
**
** Made by Karmes Lionel
** Login   <karmes_l@epitech.net>
**
** Started on  Wed Apr  6 11:24:57 2016 Karmes Lionel
** Last update Sun May  1 22:06:56 2016 Karmes Lionel
*/

#include <stdlib.h>
#include <stdio.h>
#include "syscall.h"

t_syscall	g_syscall[] =
  {
    {3, "read", {INT, STR, INT}, INT},
    {3, "write", {INT, STR, INT}, INT},
    {3, "open", {STR, INT}, INT},
    {1, "close", {INT}, INT},
    {2, "stat", {STR, ADDR}, INT},
    {2, "fstat", {INT, ADDR}, INT},
    {2, "lstat", {STR, ADDR}, INT},
    {3, "poll", {ADDR, INT, INT}, INT},
    {3, "lseek", {INT, INT, INT}, INT},
    {6, "mmap", {ADDR, INT, INT, INT, INT, INT}, ADDR},
    {3, "mprotect", {ADDR, INT, INT}, INT},
    {2, "munmap", {ADDR, INT}, INT},
    {1, "brk", {ADDR}, INT},
    {4, "rt_sigaction", {INT, ADDR, ADDR, ADDR}, INT},
    {3, "rt_sigprocmask", {INT, ADDR, ADDR}, INT},
    {1, "rt_sigreturn", {INT}, INT},
    {3, "ioctl", {INT, INT, INT}, INT},
    {4, "pread", {INT, STR, INT, INT}, INT},
    {4, "pwrite", {INT, STR, INT, INT}, INT},
    {3, "readv", {INT, ADDR, INT}, INT},
    {3, "writev", {INT, ADDR, INT}, INT},
    {2, "access", {STR, INT}, INT},
    {1, "pipe", {ADDR}, INT},
    {5, "select", {INT, ADDR, ADDR, ADDR, ADDR}, INT},
    {1, "sched_yield", {VOID}, INT},
    {5, "mremap", {ADDR, INT, INT, INT, ADDR}, ADDR},
    {3, "msync", {ADDR, INT, INT}, INT},
    {3, "mincore", {ADDR, INT, STR}, INT},
    {3, "madvise", {ADDR, INT, INT}, INT},
    {3, "shmget", {INT, INT, INT}, INT},
    {3, "shmat", {INT, ADDR, INT}, ADDR},
    {3, "shmctl", {INT, INT, ADDR}, INT},
    {1, "dup", {INT}, INT},
    {2, "dup2", {INT, INT}, INT},
    {1, "pause", {VOID}, INT},
    {2, "nanosleep", {ADDR, ADDR}, INT},
    {2, "getitimer", {INT, ADDR}, INT},
    {1, "alarm", {INT}, INT},
    {3, "setitimer", {INT, ADDR, ADDR}, INT},
    {1, "getpid", {VOID}, INT},
    {4, "sendfile", {INT, INT, ADDR, INT}, INT},
    {3, "socket", {INT, INT, INT}, INT},
    {3, "connect", {INT, ADDR, INT}, INT},
    {3, "accept", {INT, ADDR, ADDR}, INT},
    {6, "sendto", {INT, STR, INT, INT, ADDR, INT}, INT},
    {6, "recvfrom", {INT, STR, INT, INT, ADDR, ADDR}, INT},
    {3, "sendmsg", {INT, ADDR, INT}, INT},
    {3, "recvmsg", {INT, ADDR, INT}, INT},
    {2, "shutdown", {INT, INT}, INT},
    {3, "bind", {INT, ADDR, INT}, INT},
    {2, "listen", {INT, INT}, INT},
    {3, "getsockname", {INT, ADDR, ADDR}, INT},
    {3, "getpeername", {INT, ADDR, ADDR}, INT},
    {4, "socketpair", {INT, INT, INT, ADDR}, INT},
    {5, "setsockopt", {INT, INT, INT, ADDR, INT}, INT},
    {5, "getsockopt", {INT, INT, INT, ADDR, ADDR}, INT},
    {5, "clone", {ADDR, ADDR, INT, ADDR, ADDR}, INT},
    {1, "fork", {VOID}, INT},
    {1, "vfork", {VOID}, INT},
    {3, "execve", {STR, TABSTR, TABSTR}, INT},
    {1, "_exit", {INT}, VOID},
    {4, "wait4", {INT, ADDR, INT, ADDR}, INT},
    {2, "kill", {INT, INT}, INT},
    {1, "uname", {ADDR}, INT},
    {3, "semget", {INT, INT, INT}, INT},
    {3, "semop", {INT, ADDR, INT}, INT},
    {4, "semctl", {INT, INT, INT, ADDR}, INT},
    {1, "shmdt", {ADDR}, INT},
    {2, "msgget", {INT, INT}, INT},
    {4, "msgsnd", {INT, ADDR, INT, INT}, INT},
    {5, "msgrcv", {INT, STR, INT, INT, INT}, INT},
    {3, "msgctl", {INT, INT, ADDR}, INT},
    {3, "fcntl", {INT, INT, ADDR}, INT},
    {2, "flock", {INT, INT}, INT},
    {1, "fsync", {INT}, INT},
    {1, "fdatasync", {INT}, INT},
    {2, "truncate", {STR, INT}, INT},
    {2, "ftruncate", {INT, INT}, INT},
    {3, "getdents", {INT, ADDR, INT}, INT},
    {2, "getcwd", {STR, INT}, INT},
    {1, "chdir", {STR}, INT},
    {1, "fchdir", {INT}, INT},
    {2, "rename", {STR, STR}, INT},
    {2, "mkdir", {STR, INT}, INT},
    {1, "rmdir", {STR}, INT},
    {2, "creat", {STR, INT}, INT},
    {2, "link", {STR, STR}, INT},
    {1, "unlink", {STR}, INT},
    {2, "symlink", {STR, STR}, INT},
    {3, "readlink", {STR, STR, INT}, INT},
    {2, "chmod", {STR, INT}, INT},
    {2, "fchmod", {INT, INT}, INT},
    {3, "chown", {STR, INT, INT}, INT},
    {3, "fchown", {INT, INT, INT}, INT},
    {3, "lchown", {STR, INT, INT}, INT},
    {1, "umask", {INT}, INT},
    {2, "gettimeofday", {ADDR, ADDR}, INT},
    {2, "getrlimit", {INT, ADDR}, INT},
    {2, "getrusage", {INT, ADDR}, INT},
    {1, "sysinfo", {ADDR}, INT},
    {1, "times", {ADDR}, INT},
    {4, "ptrace", {INT, INT, ADDR, ADDR}, INT},
    {1, "getuid", {VOID}, INT},
    {3, "syslog", {INT, STR, INT}, INT},
    {1, "getgid", {VOID}, INT},
    {1, "setuid", {INT}, INT},
    {1, "setgid", {INT}, INT},
    {1, "geteuid", {VOID}, INT},
    {1, "getegid", {VOID}, INT},
    {2, "setpgid", {INT, INT}, INT},
    {1, "getppid", {VOID}, INT},
    {1, "getpgrp", {VOID}, INT},
    {1, "setsid", {VOID}, INT},
    {2, "setreuid", {INT, INT}, INT},
    {2, "setregid", {INT, INT}, INT},
    {2, "getgroups", {INT, ADDR}, INT},
    {2, "setgroups", {INT, ADDR}, INT},
    {3, "setresuid", {INT, INT, INT}, INT},
    {3, "getresuid", {ADDR, ADDR, ADDR}, INT},
    {3, "setresgid", {INT, INT, INT}, INT},
    {3, "getresgid", {ADDR, ADDR, ADDR}, INT},
    {1, "getpgid", {INT}, INT},
    {1, "setfsuid", {INT}, INT},
    {1, "setfsgid", {INT}, INT},
    {1, "getsid", {INT}, INT},
    {2, "capget", {ADDR, ADDR}, INT},
    {2, "capset", {ADDR, ADDR}, INT},
    {1, "rt_sigpending", {ADDR}, INT},
    {4, "rt_sigtimedwait", {ADDR, ADDR, ADDR, INT}, INT},
    {3, "rt_sigqueueinfo", {INT, INT, ADDR}, INT},
    {1, "rt_sigsuspend", {ADDR}, INT},
    {2, "sigaltstack", {ADDR, ADDR}, INT},
    {2, "utime", {STR, ADDR}, INT},
    {3, "mknod", {STR, INT, INT}, INT},
    {1, "uselib", {STR}, INT},
    {1, "personality", {INT}, INT},
    {2, "ustat", {INT, ADDR}, INT},
    {2, "statfs", {STR, ADDR}, INT},
    {2, "fstatfs", {INT, ADDR}, INT},
    {2, "sysfs", {INT, STR}, INT},
    {2, "getpriority", {INT, INT}, INT},
    {3, "setpriority", {INT, INT, INT}, INT},
    {2, "sched_setparam", {INT, ADDR}, INT},
    {2, "sched_getparam", {INT, ADDR}, INT},
    {3, "sched_setscheduler", {INT, INT, ADDR}, INT},
    {1, "sched_getscheduler", {INT}, INT},
    {1, "sched_get_priority_max", {INT}, INT},
    {1, "sched_get_priority_min", {INT}, INT},
    {2, "sched_rr_get_interval", {INT, ADDR}, INT},
    {2, "mlock", {ADDR, INT}, INT},
    {2, "munlock", {ADDR, INT}, INT},
    {1, "mlockall", {INT}, INT},
    {1, "munlockall", {VOID}, INT},
    {1, "vhangup", {VOID}, INT},
    {3, "modify_ldt", {INT, ADDR, INT}, INT},
    {2, "pivot_root", {STR, STR}, INT},
    {1, "_sysctl", {ADDR}, INT},
    {5, "prctl", {INT, INT, INT, INT, INT}, INT},
    {2, "arch_prctl", {INT, ADDR}, INT},
    {1, "adjtimex", {ADDR}, INT},
    {2, "setrlimit", {INT, ADDR}, INT},
    {1, "chroot", {STR}, INT},
    {1, "sync", {VOID}, VOID},
    {1, "acct", {STR}, INT},
    {2, "settimeofday", {ADDR, ADDR}, INT},
    {5, "mount", {STR, STR, STR, INT, ADDR}, INT},
    {2, "umount2", {STR, INT}, INT},
    {2, "swapon", {STR, INT}, INT},
    {1, "swapoff", {STR}, INT},
    {3, "reboot", {INT, INT, ADDR}, INT},
    {2, "sethostname", {STR, INT}, INT},
    {2, "setdomainname", {STR, INT}, INT},
    {1, "iopl", {INT}, INT},
    {3, "ioperm", {INT, INT, INT}, INT},
    {2, "create_module", {STR, INT}, ADDR},
    {2, "init_module", {STR, ADDR}, INT},
    {1, "delete_module", {STR}, INT},
    {1, "get_kernel_syms", {ADDR}, INT},
    {5, "query_module", {STR, INT, STR, INT, ADDR}, INT},
    {4, "quotactl", {INT, CHAR, INT, ADDR}, INT},
    {3, "nfsservctl", {INT, ADDR, ADDR}, INT},
    {5, "getpmsg", {NUL}, NUL},
    {5, "putpmsg", {NUL}, NUL},
    {5, "afs_syscall", {NUL}, NUL},
    {3, "tuxcall", {NUL}, NUL},
    {3, "security", {NUL}, NUL},
    {1, "gettid", {VOID}, INT},
    {3, "readahead", {INT, INT, INT}, INT},
    {5, "setxattr", {STR, STR, ADDR, INT, INT}, INT},
    {5, "lsetxattr", {STR, STR, ADDR, INT, INT}, INT},
    {5, "fsetxattr", {INT, STR, ADDR, INT, INT}, INT},
    {4, "getxattr", {STR, STR, ADDR, INT}, INT},
    {4, "lgetxattr", {STR, STR, ADDR, INT}, INT},
    {4, "fgetxattr", {INT, STR, ADDR, INT}, INT},
    {3, "listxattr", {STR, STR, INT}, INT},
    {3, "llistxattr", {STR, STR, INT}, INT},
    {3, "flistxattr", {INT, STR, INT}, INT},
    {2, "removexattr", {STR, STR}, INT},
    {2, "lremovexattr", {STR, STR}, INT},
    {2, "fremovexattr", {INT, STR}, INT},
    {2, "tkill", {INT, INT}, INT},
    {1, "time", {ADDR}, ADDR},
    {6, "futex", {ADDR, INT, INT, ADDR, ADDR, INT}, INT},
    {3, "sched_setaffinity", {INT, INT, ADDR}, INT},
    {3, "sched_getaffinity", {INT, INT, ADDR}, INT},
    {1, "set_thread_area", {ADDR}, INT},
    {2, "io_setup", {INT, ADDR}, INT},
    {1, "io_destroy", {ADDR}, INT},
    {5, "io_getevents", {ADDR, INT, INT, ADDR, ADDR}, INT},
    {3, "io_submit", {ADDR, INT, ADDR}, INT},
    {3, "io_cancel", {ADDR, ADDR, ADDR}, INT},
    {1, "get_thread_area", {ADDR}, INT},
    {3, "lookup_dcookie", {INT, STR, INT}, INT},
    {1, "epoll_create", {INT}, INT},
    {4, "epoll_ctl_old", {NUL}, NUL},
    {4, "epoll_wait_old", {NUL}, NUL},
    {5, "remap_file_pages", {ADDR, INT, INT, INT, INT}, INT},
    {3, "getdents64", {INT, ADDR, INT}, INT},
    {1, "set_tid_address", {ADDR}, INT},
    {1, "restart_syscall", {VOID}, INT},
    {4, "semtimedop", {INT, ADDR, INT, ADDR}, INT},
    {4, "fadvise64", {INT, INT, INT, INT}, INT},
    {3, "timer_create", {INT, ADDR, ADDR}, INT},
    {4, "timer_settime", {INT, INT, ADDR, ADDR}, INT},
    {2, "timer_gettime", {INT, ADDR}, INT},
    {1, "timer_getoverrun", {INT}, INT},
    {1, "timer_delete", {INT}, INT},
    {2, "clock_settime", {INT, ADDR}, INT},
    {2, "clock_gettime", {INT, ADDR}, INT},
    {2, "clock_getres", {INT, ADDR}, INT},
    {4, "clock_nanosleep", {INT, INT, ADDR, ADDR}, INT},
    {1, "exit_group", {INT}, VOID},
    {4, "epoll_wait", {INT, ADDR, INT, INT}, INT},
    {4, "epoll_ctl", {INT, INT, INT, ADDR}, INT},
    {3, "tgkill", {INT, INT, INT}, INT},
    {2, "utimes", {STR, ADDR}, INT},
    {5, "vserver", {NUL}, NUL},
    {6, "mbind", {ADDR, INT, INT, ADDR, INT, INT}, INT},
    {3, "set_mempolicy", {INT, ADDR, INT}, INT},
    {5, "get_mempolicy", {ADDR, ADDR, INT, INT, INT}, INT},
    {4, "mq_open", {STR, INT, INT, ADDR}, ADDR},
    {1, "mq_unlink", {STR}, INT},
    {5, "mq_timedsend", {INT, STR, INT, ADDR, ADDR}, INT},
    {5, "mq_timedreceive", {INT, STR, INT, ADDR, ADDR}, INT},
    {2, "mq_notify", {INT, ADDR}, INT},
    {3, "mq_getsetattr", {INT, ADDR, ADDR}, INT},
    {4, "kexec_load", {INT, INT, ADDR, INT}, INT},
    {4, "waitid", {INT, INT, ADDR, INT}, INT},
    {5, "add_key", {STR, STR, ADDR, INT, INT}, INT},
    {4, "request_key", {STR, STR, STR, INT}, INT},
    {2, "keyctl", {INT, ADDR}, INT},
    {3, "ioprio_set", {INT, INT, INT}, INT},
    {2, "ioprio_get", {INT, INT}, INT},
    {1, "inotify_init", {VOID}, INT},
    {3, "inotify_add_watch", {INT, STR, INT}, INT},
    {2, "inotify_rm_watch", {INT, INT}, INT},
    {4, "migrate_pages", {INT, INT, ADDR, ADDR}, INT},
    {4, "openat", {INT, STR, INT, ADDR}, INT},
    {3, "mkdirat", {INT, STR, INT}, INT},
    {4, "mknodat", {INT, STR, INT, INT}, INT},
    {5, "fchownat", {INT, STR, INT, INT, INT}, INT},
    {3, "futimesat", {INT, STR, ADDR}, INT},
    {4, "newfstatat", {NUL}, NUL},
    {3, "unlinkat", {INT, STR, INT}, INT},
    {4, "renameat", {INT, STR, INT, STR}, INT},
    {5, "linkat", {INT, STR, INT, STR, INT}, INT},
    {3, "symlinkat", {STR, INT, STR}, INT},
    {4, "readlinkat", {INT, STR, STR, INT}, INT},
    {4, "fchmodat", {INT, STR, INT, INT}, INT},
    {4, "faccessat", {INT, STR, INT, INT}, INT},
    {6, "pselect6", {INT, ADDR, ADDR, ADDR, ADDR, ADDR}, INT},
    {4, "ppoll", {ADDR, INT, ADDR, ADDR}, INT},
    {1, "unshare", {INT}, INT},
    {2, "set_robust_list", {ADDR, INT}, INT},
    {3, "get_robust_list", {INT, ADDR, ADDR}, INT},
    {6, "splice", {INT, ADDR, INT, ADDR, INT, INT}, INT},
    {4, "tee", {INT, INT, INT, INT}, INT},
    {4, "sync_file_range", {INT, INT, INT, INT}, INT},
    {4, "vmsplice", {INT, ADDR, INT, INT}, INT},
    {6, "move_pages", {INT, INT, ADDR, ADDR, ADDR, INT}, INT},
    {4, "utimensat", {INT, STR, ADDR, INT}, INT},
    {5, "epoll_pwait", {INT, ADDR, INT, INT, ADDR}, INT},
    {3, "signalfd", {INT, ADDR, INT}, INT},
    {2, "timerfd_create", {INT, INT}, INT},
    {2, "eventfd", {INT, INT}, INT},
    {4, "fallocate", {INT, INT, INT, INT}, INT},
    {4, "timerfd_settime", {INT, INT, ADDR, ADDR}, INT},
    {2, "timerfd_gettime", {INT, ADDR}, INT},
    {4, "accept4", {INT, ADDR, ADDR, INT}, INT},
    {3, "signalfd4", {INT, ADDR, INT}, INT},
    {2, "eventfd2", {INT, INT}, INT},
    {1, "epoll_create1", {INT}, INT},
    {3, "dup3", {INT, INT, INT}, INT},
    {2, "pipe2", {ADDR, INT}, INT},
    {1, "inotify_init1", {INT}, INT},
    {4, "preadv", {INT, ADDR, INT, INT}, INT},
    {4, "pwritev", {INT, ADDR, INT, INT}, INT},
    {4, "rt_tgsigqueueinfo", {INT, INT, INT, ADDR}, INT},
    {5, "perf_event_open", {NUL}, NUL},
    {5, "recvmmsg", {INT, ADDR, INT, INT, ADDR}, INT},
    {2, "fanotify_init", {INT, INT}, INT},
    {5, "fanotify_mark", {INT, INT, INT, INT, STR}, INT},
    {4, "prlimit64", {INT, INT, ADDR, ADDR}, INT},
    {5, "name_to_handle_at", {INT, STR, ADDR, ADDR, INT}, INT},
    {3, "open_by_handle_at", {INT, ADDR, INT}, INT},
    {2, "clock_adjtime", {INT, ADDR}, INT},
    {1, "syncfs", {INT}, INT},
    {4, "sendmmsg", {INT, ADDR, INT, INT}, INT},
    {2, "setns", {INT, INT}, INT},
    {3, "getcpu", {ADDR, ADDR, ADDR}, INT},
    {6, "process_vm_readv", {INT, ADDR, INT, ADDR, INT, INT}, INT},
    {6, "process_vm_writev", {INT, ADDR, INT, ADDR, INT, INT}, INT},
    {5, "kcmp", {INT, INT, INT, INT, INT}, INT},
    {3, "finit_module", {INT, STR, INT}, INT},
    {3, "sched_setattr", {INT, ADDR, INT}, INT},
    {4, "sched_getattr", {INT, ADDR, INT, INT}, INT},
    {5, "renameat2", {INT, STR, INT, STR, INT}, INT},
    {0, NULL, {NUL}, NUL},
  };

int	is_syscall(long long unsigned int orig_rax)
{
  if ((int)orig_rax != -1 && (int)orig_rax < 317)
    return (1);
  return (0);
}

void	init_tab_reg(unsigned long long int *tab_reg,
		     const struct user_regs_struct *regs)
{
  tab_reg[0] = regs->rdi;
  tab_reg[1] = regs->rsi;
  tab_reg[2] = regs->rdx;
  tab_reg[3] = regs->rcx;
  tab_reg[4] = regs->r8;
  tab_reg[5] = regs->r9;
}

void				print_syscall(const struct user_regs_struct
					      *regs)
{
  unsigned long long int	tab_reg[6];
  int				i;

  init_tab_reg(&tab_reg[0], regs);
  i = 0;
  fprintf(stdout, "Syscall %s(", g_syscall[regs->orig_rax].name);
  while (i + 1 < g_syscall[regs->orig_rax].args)
    {
      fprintf(stdout, "0x%0llx, ", tab_reg[i]);
      ++i;
    }
  if (g_syscall[regs->orig_rax].returnType == VOID)
    fprintf(stdout, "0x%0llx) = ?\n", tab_reg[i]);
  else
    fprintf(stdout, "0x%0llx) = 0x%0llx\n", tab_reg[i], regs->rax);
}
